spring:
  jpa:
   database: POSTGRESQL
    show-sql: true
    hibernate:
     ddl-auto: create
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fornecedor
    username: postgres
    password: postgres
		
